version: '3.1'
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: TodoDB
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: './backend'
      dockerfile: './Dockerfile'
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_PASSWORD=mysecretpassword
      - JWT_SECRET=redblueyellow
      - TOKEN_LIFE=5m
      - PRODUCTION=true